// <auto-generated />
namespace lab_41_entity_code_first.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class movedb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movedb));
        
        string IMigrationMetadata.Id
        {
            get { return "201910031352204_movedb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
